<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_M nhn s M nhn s H v tn H v tn Tn ng nhp_2f55dd</name>
   <tag></tag>
   <elementGuidId>49dafd07-93d2-483c-8480-f90a2cf585fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.right-modal_contentContainer__1CtFK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='edit-staff-form']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right-modal_contentContainer__1CtFK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mã nhân sự *Mã nhân sự *Họ và tên *Họ và tên *Tên đăng nhập *Tên đăng nhập *Đặt lại mật khẩuSố điện thoại làm việc Số điện thoại làm việc EmailEmailQuản lý trực tiếp *Quản lý trực tiếp *Vị trí làm việc *Vị trí làm việc *Phòng ban *Phòng ban *Trạng tháiTrạng tháiNhóm quyềnNhóm quyềnGhi chúGhi chú</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-staff-form&quot;)/div[@class=&quot;right-modal_contentContainer__1CtFK&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit-staff-form']/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sửa nhân sự'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sau'])[1]/following::div[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
